global:
  checkNewVersion: true

accessLog:
  filePath: /var/log/traefik/access.log

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

api:
  dashboard: true
  debug: true

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: hello@tifa.dev
      storage: /etc/traefik/certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

entryPoints:
  # mysql:
  #   address: :3306
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
